### ISSUE TITLE
Plugin skips too much on particular songs.

### ISSUE THREAD

**Issue by AsVHEn** [kpcee/deadbeef-silence_remover#1]
Hi,
firstly, thank you for your plugin.
Listening to "AKUFEN - My way" which is an album full micro silences, I have noticed a lot of skipping. It's particularly true with "04 - Deck the house", "05 - Wet floors", "07 - In dog we trust" or "08 - Jeep sex".
I don't know if its possible to fix this without broke plugin, or simply it doesn't happen with more albums :smile:.

**Comment by kpcee** [comment]
At the moment the values are still hardcoded and must be adjusted directly in the source. If silence is falsely detected within a song, you can try setting the threshold from 0.000100 to 0. If that doesn't help either, just comment out the following lines and recompile the plugin to remove the jumping within a song.

```
else if ( middle < 0.000100 && percent >= 10.0 && percent <= 90.0 )
    {
        deadbeef->playback_set_pos( percent + 0.5 );
        // printf( "++ Fast forward: Amplitude: %f / percent played: %f / play pos: %f / song length: %f\n", middle, percent, pos, length );
    }
```

**Comment by AsVHEn** [comment]
Ok, no problem, I was editing it a lot to add anothers foobar's plugins functionalities :smile: , thank you.

**Comment by kpcee** [comment]
In the new version you can set the threshold values yourself in the plugin settings or deactivate individual functions with -1. This way you can easily solve the described problem.
